version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -q -U naming-service@oplabs-local-web.iam -d naming-service']
    volumes:
      - ./setup-local-db.sql:/docker-entrypoint-initdb.d/setup-local-db.sql
    ports:
      - '5432:5432'

  redis:
    image: 'redis:latest'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 2s
    volumes:
      - redis_data:/data/redis
    ports:
      - 6479:6379

  api:
    build:
      # context: ../../
      dockerfile: Dockerfile
      # target: naming-service
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=naming-service
      - MIGRATE_DB_USER=naming-service@oplabs-local-web.iam
      - DB_USER=naming-service@oplabs-local-web.iam
    healthcheck:
      test: curl http://0.0.0.0:7300/api/v0/healthz
    ports:
      - 7400:7300
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:
